plugins {
	id 'java'
	alias(libs.plugins.spring.boot)
	alias(libs.plugins.spring.dependency.management)
}

group = 'com.discovery'
version = '1.0.0'
description = 'Eureka service registry'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(libs.versions.java.get() as int)
	}
}

repositories {
	mavenCentral()
}

dependencyManagement {
	imports {
		mavenBom libs.spring.cloud.dependencies.get().toString()
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-restclient'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

bootJar {
	archiveFileName = 'application.jar'
}

jar {
	enabled = false
}

test {
	useJUnitPlatform()
}
