services:

# Eureka-Discovery-service
  eureka-discovery-service:
#    image: srik1980/eureka-discovery-service:1.0
    build:
      context: .
    container_name: eureka-discovery-service
#    depends_on:
#      - mariadb
#      - phpmyadmin
    ports:
      - "9111:9111"
#    environment:
#      - SPRING_DATASOURCE_USERNAME=theuser
#      - SPRING_DATASOURCE_PASSWORD=theuser
#      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/videodb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create


volumes:
  mariadb:
    driver: local
