spring:
  profiles.active: ${SPRING_ACTIVE_PROFILE:dev}
  application:
    name: eureka-discovery-service

server:
  port: ${SERVER_PORT:9111}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IPADDRESS:true}
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

# Spring Security
#spring:
#  security:
#    user:
#      name: admin
#      password: password